export const allTarotImages = [
  { "src": "/images/c01.jpg" },
  { "src": "/images/c02.jpg" },
  { "src": "/images/c03.jpg" },
  { "src": "/images/c04.jpg" },
  { "src": "/images/c05.jpg" },
  { "src": "/images/c06.jpg" },
  { "src": "/images/c07.jpg" },
  { "src": "/images/c08.jpg" },
  { "src": "/images/c09.jpg" },
  { "src": "/images/c10.jpg" },
  { "src": "/images/c11.jpg" },
  { "src": "/images/c12.jpg" },
  { "src": "/images/c13.jpg" },
  { "src": "/images/c14.jpg" },
  { "src": "/images/m00.jpg" },
  { "src": "/images/m01.jpg" },
  { "src": "/images/m02.jpg" },
  { "src": "/images/m03.jpg" },
  { "src": "/images/m04.jpg" },
  { "src": "/images/m05.jpg" },
  { "src": "/images/m06.jpg" },
  { "src": "/images/m07.jpg" },
  { "src": "/images/m08.jpg" },
  { "src": "/images/m09.jpg" },
  { "src": "/images/m10.jpg" },
  { "src": "/images/m11.jpg" },
  { "src": "/images/m12.jpg" },
  { "src": "/images/m13.jpg" },
  { "src": "/images/m14.jpg" },
  { "src": "/images/m15.jpg" },
  { "src": "/images/m16.jpg" },
  { "src": "/images/m17.jpg" },
  { "src": "/images/m18.jpg" },
  { "src": "/images/m19.jpg" },
  { "src": "/images/m20.jpg" },
  { "src": "/images/m21.jpg" },
  { "src": "/images/p01.jpg" },
  { "src": "/images/p02.jpg" },
  { "src": "/images/p03.jpg" },
  { "src": "/images/p04.jpg" },
  { "src": "/images/c05.jpg" },
  { "src": "/images/p06.jpg" },
  { "src": "/images/p07.jpg" },
  { "src": "/images/p08.jpg" },
  { "src": "/images/p09.jpg" },
  { "src": "/images/p10.jpg" },
  { "src": "/images/p11.jpg" },
  { "src": "/images/p12.jpg" },
  { "src": "/images/p13.jpg" },
  { "src": "/images/p14.jpg" },
  { "src": "/images/s01.jpg" },
  { "src": "/images/s02.jpg" },
  { "src": "/images/s03.jpg" },
  { "src": "/images/s04.jpg" },
  { "src": "/images/s05.jpg" },
  { "src": "/images/s06.jpg" },
  { "src": "/images/s07.jpg" },
  { "src": "/images/s08.jpg" },
  { "src": "/images/s09.jpg" },
  { "src": "/images/s10.jpg" },
  { "src": "/images/s11.jpg" },
  { "src": "/images/s12.jpg" },
  { "src": "/images/s13.jpg" },
  { "src": "/images/s14.jpg" },
  { "src": "/images/w01.jpg" },
  { "src": "/images/w02.jpg" },
  { "src": "/images/w03.jpg" },
  { "src": "/images/w04.jpg" },
  { "src": "/images/w05.jpg" },
  { "src": "/images/w06.jpg" },
  { "src": "/images/w07.jpg" },
  { "src": "/images/wo8.jpg" },
  { "src": "/images/w09.jpg" },
  { "src": "/images/w10.jpg" },
  { "src": "/images/w11.jpg" },
  { "src": "/images/w12.jpg" },
  { "src": "/images/w13.jpg" },
  { "src": "/images/w14.jpg" },

]

export const cardImages = [
  { "src": "/images/c01.jpg", matched: false},
  { "src": "/images/c02.jpg", matched: false},
  { "src": "/images/c03.jpg", matched: false },
  { "src": "/images/c04.jpg", matched: false },
  { "src": "/images/c05.jpg", matched: false },
  { "src": "/images/c06.jpg", matched: false },
]

